name: zimbra_api
description: Zimbra SOAP API library in Dart language.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  crypto: ^3.0.2
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  faker: ^2.0.0
  test: ^1.16.0
